let book = prompt("mời bạn nhập tên sách");
let tacGia = prompt("mời bạn nhập tên tác giả");
let namXuatBan = +prompt("mời bạn nhập năm xuất bản");
let price = +prompt("mời bạn nhập giá tiền một cuốn sách");
let soLuong = +prompt("mời bạn nhập số lượng nhập kho");
console.log(`---PHIẾU NHẬP KHO---`);
let maTacGia = tacGia.substring(0, 3);
let soNgauNhien = ((Math.random() * 1000) + 1);
let maSach = `${maTacGia}${namXuatBan}-${soNgauNhien}`;
console.log(`Mã sách ${maSach}`);
book = book.trim().toUpperCase();
console.log(`Tên sách : ${book}`);
tacGia = tacGia.toUpperCase();
console.log(`Tác giả ${tacGia}`);
console.log(`Năm xuất bản : ${namXuatBan}`);
let years = 2026;
let tuoiSach = years - namXuatBan;
console.log(`Tuổi của sách : ${tuoiSach}`);
let tongGiaTri = price * soLuong;
console.log(`Tổng giá trị : ${tongGiaTri} đ`);
let keSach = Math.floor(((Math.random() * 10) + 1));
console.log(`Ngăn kệ gợi ý : kệ số ${keSach}`);